version: "3"
services:
  web:
    image: nginx:alpine
    volumes:
      - ./src/:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=finsweet.com
      - NGINX_PORT=80